### ISSUE TITLE
No endpoint found

### ISSUE THREAD

**Issue by mcdermott94** [mrwnwttk/audius-dl#3]
On some tracks I get the below issue. Is there any fix for this?

Please enter a link: https://audius.co/nerouk/frankie-goes-to-hollywood-relax-nero-edit-322730
API endpoint: https://discoveryprovider.audius.prod-us-west-2.staked.cloud
Number of segments: 32
Node endpoints: https://creatornode.audius.co / https://creatornode2.audius.co / https://creatornode3.audius.co
Checking for available enpoints...
https://creatornode.audius.co - Failed!
https://creatornode2.audius.co - Failed!
https://creatornode3.audius.co - Failed!
Not a single working endpoint found! Exiting...
Exit status: 0

**Comment by mrwnwttk** [comment]
Nope. Once a track (or even just a single segment) has been blacklisted by the endpoint nodes it's basically game over.
